name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a ejecutar'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Terraform Init
        working-directory: app/infra
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        working-directory: app/infra
        run: terraform plan ${{ github.event.inputs.action == 'destroy' && '-destroy' || '' }}
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_railway_token: ${{ secrets.RAILWAY_TOKEN }}
          TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TF_VAR_gh_repo: ${{ secrets.GH_REPO }}

      - name: Terraform Apply / Destroy
        working-directory: app/infra
        run: terraform ${{ github.event.inputs.action }} -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          TF_VAR_railway_token: ${{ secrets.RAILWAY_TOKEN }}
          TF_VAR_mysql_root_password: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TF_VAR_gh_repo: ${{ secrets.GH_REPO }}